name: digi_gold
description: "VMurugan - Digital Gold Trading Platform"
publish_to: 'none'
version: 1.3.1+15

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  firebase_core: ^3.15.1
  firebase_auth: ^5.3.3
  url_launcher: ^6.2.2
  webview_flutter: ^4.4.2
  shared_preferences: ^2.5.3
  google_fonts: ^6.1.0
  sqflite: ^2.4.2
  path: ^1.9.1
  pdf: ^3.11.1
  path_provider: ^2.1.4
  intl: ^0.20.2
  # Omniware Payment Gateway SDK
  omniware_payment_gateway_totalxsoftware: ^1.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.3.2  # Added for splash screen

flutter:
  uses-material-design: true
  assets:
    - assets/

# Flutter Launcher Icons Configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/vm_launcher_centered.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/vm_launcher_centered.png"
  min_sdk_android: 21
  remove_alpha_ios: true

# Flutter Native Splash Configuration
flutter_native_splash:
  color: "#DC143C"                      # Background color (red)
  android: true
  ios: true
  web: false
  fullscreen: true                       # Fullscreen splash
